name: json

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  java:
    runs-on: ubuntu-latest
    name: A job to say hello
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@master
        with:
           node-version: ${{ matrix.node-version }}
      - name: install 
        run: |
            npm install
            npm ci
#       - name: install
#         run: |
#             npm install @actions/core
#             npm install @actions/github
      - name: build
        run: |
            npm run build
            npm run test
      - name: node
        run: |
            node index.js
          
#        steps:
#           - name: 'pre-deployment'
#             id: pre-deployment
#             
#       - name: Hello world action step
#         id: hello
#         uses: action/javascript-actions@main
#         with:
#           who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
#       - name: Get the output time
#         run: echo "success"
