on: [push]

jobs:
  java:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@main
        with:
           node-version: ${{ matrix.node-version }}
      - name: install 
        run: |
            npm install
            npm ci
            npm install @actions/core
            npm install @actions/github
            run: |
            npm run build
            npm run test
            run: |
            node index.js
            steps:
#       - name: Hello world action step
#         id: hello
#         uses: action/hello-jscript-action@v1.1
#         with:
#           who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
